spring:
  datasource:
    name: service-car
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whys?characterEncoding=UTF-8
    username: root
    password: 123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    druid:
      # 连接池最大使用连接数
      max-active: 20
      # 初始化连接大小
      initial-size: 1
      # 获取连接最大等待时间
      max-wait: 60000
      # 连接池最小空闲
      min-idle: 3
      # 自动清除无用连接
      remove-abandoned: true
      # 清除无用连接的等待时间
      remove-abandoned-timeout: 180
      # 连接属性
      connection-properties: clientEncoding=UTF-8
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙

mybatis:
    type-aliases-package: com.hdsx.car.model
    mapper-locations: classpath*:mapper/*.xml


pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# swagger2
swagger2.package: com.hdsx.car.car
ss_url: http://localhost:8104/success